### PR TITLE
Added toolchain file and build instruction for iOS

### PR DESCRIPTION
**Pull request by Gummilion**
Created toolchain file and build instructions for build SRT code for iOS per #266 
Updated configure script to prevent specifying explicit SSL path if toolchain used.

### CODE REVIEW

**Comment by alexpokotilo** [comment]
@rndi could you please check why "continuous-integration/appveyor/pr" check is pending for this pull request. As I see another new pull request has the same problem https://github.com/Haivision/srt/pull/288
This pull request is IOS part of our company contribution to SRT. You have already merged Android part of this request https://github.com/Haivision/srt/pull/278

**Comment by rndi** [comment]
I will look into it; appveyor has been acting up recently. Thank you for the contribution @alexpokotilo, hopefully this will be sorted out shortly!

**Comment by alexpokotilo** [comment]
@rndi appveyor failed with following message: 
**(ClCompile target) -> 
  C:\projects\srt\srtcore\srt_compat.c(43): error C2143: syntax error : missing '{' before 'const' [C:\projects\srt\srt_virtual.vcxproj]**
But we don't change srt_compat.c in this build at all

**Comment by rndi** [comment]
Sorry @alexpokotilo , this got broken in #285 and slipped past us because Appveyor was stuck (horrible excuse, I know). I opened PR #290 that should resolve the problem going forward. I don't think you need to rebase this PR to get Appveyor check passed because @Gummilion's changes are not touching anything Windows-related. But it would be good if @ethouris gives his blessings though since he was part of the discussion on #266 thread.

**Comment by rndi** [comment]
On another note, @Gummilion , could you please take a look at #229 and give you blessing to MPL change if you are ok with it?

Much appreciated!

**Comment by Gummilion** [comment]
@rndi - OK, voted for it.

**Comment by rndi** [comment]
Thanks @Gummilion !

**Comment by alexpokotilo** [comment]
@rndi as #290 integrated and we push only docs please merge this

**Comment by Gummilion** [comment]
iOS.cmake is passed to configure with `--cmake-toolchain-file=scripts/iOS.cmake` parameter, as mentioned in build_iOS.md, and configure script pass it to CMake with **-D[CMAKE_TOOLCHAIN_FILE](https://cmake.org/cmake/help/v3.10/variable/CMAKE_TOOLCHAIN_FILE.html)** option. Probably we could add some specific parameter (like `--build-ios`) to configure, but I'm not sure whether it needed.
