### ISSUE TITLE
[BUG] build error on tests

### ISSUE THREAD

**Issue by dbermond** [Haivision/srt#1019]
**Describe the bug**
I'm getting this build error when trying to build srt using the current git master:
```
[ 40%] Building CXX object CMakeFiles/srt-test-multiplex.dir/testing/testmedia.cpp.o
In file included from /build/srt-git/src/srt/testing/testmedia.cpp:26:
/build/srt-git/src/srt/srtcore/netinet_any.h: In constructor ‘sockaddr_any::sockaddr_any(int)’:
/build/srt-git/src/srt/srtcore/netinet_any.h:40:37: warning: ‘void* memset(void*, int, size_t)’ clearing an object of non-trivial type ‘struct sockaddr_any’; use assignment or value-initialization instead [-Wclass-memaccess]
   40 |         memset(this, 0, sizeof *this);
      |                                     ^
/build/srt-git/src/srt/srtcore/netinet_any.h:28:8: note: ‘struct sockaddr_any’ declared here
   28 | struct sockaddr_any
      |        ^~~~~~~~~~~~
/build/srt-git/src/srt/testing/testmedia.cpp: In constructor ‘UdpTarget::UdpTarget(std::string, int, const std::map<std::__cxx11::basic_string<char>, std::__cxx11::basic_string<char> >&)’:
/build/srt-git/src/srt/testing/testmedia.cpp:1275:43: error: conversion from ‘in_addr_t’ {aka ‘unsigned int’} to non-scalar type ‘in_addr’ requested
 1275 |             in_addr addr = maddr.sin_addr.s_addr;
      |                            ~~~~~~~~~~~~~~~^~~~~~
/build/srt-git/src/srt/testing/testmedia.cpp:1278:25: error: ‘status_error’ was not declared in this scope
 1278 |             if ( res == status_error )
      |                         ^~~~~~~~~~~~
make[2]: *** [CMakeFiles/srt-test-multiplex.dir/build.make:76: CMakeFiles/srt-test-multiplex.dir/testing/testmedia.cpp.o] Error 1
make[2]: Leaving directory '/build/srt-git/src/build'
make[1]: *** [CMakeFiles/Makefile2:102: CMakeFiles/srt-test-multiplex.dir/all] Error 2
make[1]: Leaving directory '/build/srt-git/src/build'
make: *** [Makefile:130: all] Error 2
make: Leaving directory '/build/srt-git/src/build'
```

**To Reproduce**
```
$ git clone https://github.com/Haivision/srt.git
$ cmake -B build -S srt -DENABLE_TESTING='True'
$ make -C build -j1
```

**Expected behavior**
Build success.

**Screenshots**
Not applicable.

**Desktop (please provide the following information):**
 - OS: Arch Linux x86_64
 - SRT Version / commit ID: git master, current at acd703f7348345248f7dfe68f1ead20c840c6250.
- Compiler: gcc 9.2.0

**Additional context**
- This is caused by commit acd703f7348345248f7dfe68f1ead20c840c6250.
- Reverting commit acd703f7348345248f7dfe68f1ead20c840c6250 "fixes" the issue.
- Disabling tests with `-DENABLE_TESTING='False'` also "fixes" the issue.
