### ISSUE TITLE
[BUG] api.cpp:2881:7: error: reference to 'this_thread' is ambiguous

### ISSUE THREAD

**Issue by kevleyski** [Haivision/srt#1571]
**Describe the bug**
api.cpp:2881:7: error: reference to 'this_thread' is ambiguous

Build on MacOS 10.15.6
brew install cmake
brew install openssl

**To Reproduce**
1. Configure

export OPENSSL_ROOT_DIR=$(brew --prefix openssl)
export OPENSSL_LIB_DIR=$(brew --prefix openssl)"/lib"
export OPENSSL_INCLUDE_DIR=$(brew --prefix openssl)"/include"
./configure

2. Make (failure)

make

**Desktop (please provide the following information):**
 - OS: MacOS 10.15.6
 - SRT: Tip of https://github.com/Haivision/srt 23 Sep 12pm Sydney time 

**Additional context**

**Comment by kevleyski** [comment]
Issue might be when using latest Xcode Version 12.2 beta (12B5018i)

**Comment by kevleyski** [comment]
namespace might be conflicting with std:: vs srt::sync::

**Comment by maxsharabayko** [comment]
Fixed by #1572
