### PR TITLE
Fixes #1571 srt::sync:: namespace qualification for this_thread

### LINKED ISSUE #1571: [BUG] api.cpp:2881:7: error: reference to 'this_thread' is ambiguous
**Describe the bug**
api.cpp:2881:7: error: reference to 'this_thread' is ambiguous

Build on MacOS 10.15.6
brew install cmake
brew install openssl

**To Reproduce**
1. Configure

export OPENSSL_ROOT_DIR=$(brew --prefix openssl)
export OPENSSL_LIB_DIR=$(brew --prefix openssl)"/lib"
export OPENSSL_INCLUDE_DIR=$(brew --prefix openssl)"/include"
./configure

2. Make (failure)

make

**Desktop (please provide the following information):**
 - OS: MacOS 10.15.6
 - SRT: Tip of https://github.com/Haivision/srt 23 Sep 12pm Sydney time 

**Additional context**

### PR DESCRIPTION
**Pull request by kevleyski**
this_thread was ambiguous with the current llvm::clang toolchan in Xcode beta 12.2

### CODE REVIEW

**Review by maxsharabayko — APPROVED** [review]

**Comment by maxsharabayko** [comment]
@kevleyski Thank you for the fix!
