### ISSUE TITLE
[BUILD] srt does not build with nettle 4.0

### ISSUE THREAD

**Issue by fundawang** [Haivision/srt#3316]
When building with nettle 4.0, it produces following error:
```
026-05-10 06:40:18 In file included from /home/lkp/rpmbuild/BUILD/srt-1.4.4/haicrypt/hcrypt.h:52,
2026-05-10 06:40:18                  from /home/lkp/rpmbuild/BUILD/srt-1.4.4/haicrypt/hcrypt.c:32:
2026-05-10 06:40:18 /home/lkp/rpmbuild/BUILD/srt-1.4.4/haicrypt/cryspr.h:42:25: error: field 'aes_kek' has incomplete type
2026-05-10 06:40:18    42 |         CRYSPR_AESCTX   aes_kek;                /* Key Encrypting Key (KEK) */
2026-05-10 06:40:18       |                         ^~~~~~~
2026-05-10 06:40:18 /home/lkp/rpmbuild/BUILD/srt-1.4.4/haicrypt/cryspr.h:43:25: error: array type has incomplete element type 'CRYSPR_AESCTX' {aka 'struct aes_ctx'}
2026-05-10 06:40:18    43 |         CRYSPR_AESCTX   aes_sek[2];             /* even/odd Stream Encrypting Key (SEK) */
2026-05-10 06:40:18       |                         ^~~~~~~
```

https://github.com/gnutls/nettle/blob/5d7cdca95baf6b5f1466331ef1b7de42d7ba2edc/NEWS#L82
> Deleted the old struct aes_ctx, and all functions operating on it. Use the fixed key size interfaces instead, e.g., struct aes256_ctx, introduced in Nettle-3.0.

**Comment by yaneti** [comment]
https://gitlab.com/gnutls/gnutls/-/merge_requests/2075  the compatible migration done for gnutls, 
Don't know if there is a better migration guide elsewhere.
