### ISSUE TITLE
Build error on GCC 4.8.5

### ISSUE THREAD

**Issue by maxsharabayko** [Haivision/srt#3048]
Compiler: gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-44) 

```shell
/srt/haicrypt/cryspr.c: In function 'crysprFallback_MsEncrypt':
/srt/haicrypt/cryspr.c:473:6: error: 'for' loop initial declarations are only allowed in C99 mode
      for (size_t i = 0; i < sizeof(aad) / 4; ++i)
      ^
/srt/haicrypt/cryspr.c:473:6: note: use option -std=c99 or -std=gnu99 to compile your code
/srt/haicrypt/cryspr.c: In function 'crysprFallback_MsDecrypt':
/srt/haicrypt/cryspr.c:619:7: error: 'for' loop initial declarations are only allowed in C99 mode
       for (size_t i = 0; i < sizeof(aad) / 4; ++i)
```

Introduced in PR #2962.

**Comment by maxsharabayko** [comment]
A current workaround is to add `-DCMAKE_C_FLAGS='-std=c99'` to the cmake command.
I think `-std=c99` can be made default in the CMake file of srt.
Or take the initialization out of the `for` loop.

**Comment by ethouris** [comment]
As per compiler requirements, gcc 4.8.0 could be the oldest supported from this line and it supports C99. It can be kinda complicated, but I think it's worth it.

Do not use `-std=c99`. [Be more portable](https://cmake.org/cmake/help/v3.1/variable/CMAKE_C_STANDARD.html), at least for cmake older than 3.1.

**Comment by maxsharabayko** [comment]
So `C_STANDARD` if CMake >= 3.1, else `set (CMAKE_C_FLAGS .... -std=c99)` or `list(APPEND SRT_EXTRA_CFLAGS "-std=c99")`

**Comment by maxsharabayko** [comment]
Hm, `CXX_STANDARD` seems to be introduced in CMake 3.1, but we use it in this macro without any check for CMake version:
```cmake
macro(srt_set_stdcxx targetname spec)
	set (stdcxxspec ${spec})
	if (NOT "${stdcxxspec}" STREQUAL "")
		if (FORCE_CXX_STANDARD_GNUONLY)
			target_compile_options(${targetname} PRIVATE -std=c++${stdcxxspec})
			message(STATUS "C++ STD: ${targetname}: forced C++${stdcxxspec} standard - GNU option: -std=c++${stdcxxspec}")
		else()
			set_target_properties(${targetname} PROPERTIES CXX_STANDARD ${stdcxxspec})
			message(STATUS "C++ STD: ${targetname}: forced C++${stdcxxspec} standard - portable way")
		endif()
	else()
		message(STATUS "APP: ${targetname}: using default C++ standard")
	endif()
endmacro()
```

**Comment by maxsharabayko** [comment]
```cmake
macro(srt_set_stdc targetname spec)
	set (stdcspec ${spec})
	if (NOT "${stdcspec}" STREQUAL "")
		if (CMAKE_MAJOR_VERSION LESS 3)
			target_compile_options(${targetname} PRIVATE -std=c${stdcspec})
			message(STATUS "C STD: ${targetname}: forced C${stdcxxspec} standard - GNU option: -std=c${stdcspec}.")
		else()
			set_target_properties(${targetname} PROPERTIES C_STANDARD ${stdcspec})
			message(STATUS "C STD: ${targetname}: forced C${stdcxxspec} standard - portable way.")
		endif()
	else()
		message(STATUS "APP: ${targetname}: using default C standard.")
	endif()
endmacro()
```

**Comment by ethouris** [comment]
You can make a common version with additional variable to specify whether C or C++.
