### PR TITLE
Added fixes for assignment copy compliance

### LINKED ISSUE #1019: [BUG] build error on tests
**Describe the bug**
I'm getting this build error when trying to build srt using the current git master:
```
[ 40%] Building CXX object CMakeFiles/srt-test-multiplex.dir/testing/testmedia.cpp.o
In file included from /build/srt-git/src/srt/testing/testmedia.cpp:26:
/build/srt-git/src/srt/srtcore/netinet_any.h: In constructor ‘sockaddr_any::sockaddr_any(int)’:
/build/srt-git/src/srt/srtcore/netinet_any.h:40:37: warning: ‘void* memset(void*, int, size_t)’ clearing an object of non-trivial type ‘struct sockaddr_any’; use assignment or value-initialization instead [-Wclass-memaccess]
   40 |         memset(this, 0, sizeof *this);
      |                                     ^
/build/srt-git/src/srt/srtcore/netinet_any.h:28:8: note: ‘struct sockaddr_any’ declared here
   28 | struct sockaddr_any
      |        ^~~~~~~~~~~~
/build/srt-git/src/srt/testing/testmedia.cpp: In constructor ‘UdpTarget::UdpTarget(std::string, int, const std::map<std::__cxx11::basic_string<char>, std::__cxx11::basic_string<char> >&)’:
/build/srt-git/src/srt/testing/testmedia.cpp:1275:43: error: conversion from ‘in_addr_t’ {aka ‘unsigned int’} to non-scalar type ‘in_addr’ requested
 1275 |             in_addr addr = maddr.sin_addr.s_addr;
      |                            ~~~~~~~~~~~~~~~^~~~~~
/build/srt-git/src/srt/testing/testmedia.cpp:1278:25: error: ‘status_error’ was not declared in this scope
 1278 |             if ( res == status_error )
      |                         ^~~~~~~~~~~~
make[2]: *** [CMakeFiles/srt-test-multiplex.dir/build.make:76: CMakeFiles/srt-test-multiplex.dir/testing/testmedia.cpp.o] Error 1
make[2]: Leaving directory '/build/srt-git/src/build'
make[1]: *** [CMakeFiles/Makefile2:102: CMakeFiles/srt-test-multiplex.dir/all] Error 2
make[1]: Leaving directory '/build/srt-git/src/build'
make: *** [Makefile:130: all] Error 2
make: Leaving directory '/build/srt-git/src/build'
```

**To Reproduce**
```
$ git clone https://github.com/Haivision/srt.git
$ cmake -B build -S srt -DENABLE_TESTING='True'
$ make -C build -j1
```

**Expected behavior**
Build success.

**Screenshots**
Not applicable.

**Desktop (please provide the following information):**
 - OS: Arch Linux x86_64
 - SRT Version / commit ID: git master, current at acd703f7348345248f7dfe68f1ead20c840c6250.
- Compiler: gcc 9.2.0

**Additional context**
- This is caused by commit acd703f7348345248f7dfe68f1ead20c840c6250.
- Reverting commit acd703f7348345248f7dfe68f1ead20c840c6250 "fixes" the issue.
- Disabling tests with `-DENABLE_TESTING='False'` also "fixes" the issue.

### PR DESCRIPTION
**Pull request by ethouris**
Fixes #1019, #1018 
(part of the fixes are provided additionally on #1006)

Changes:

1. Added copy-assignment operator for `SrtCongestion`.

There was a hidden problem there, as the copying was predicted to copy just the name, but the pointer to the managed object was set to 0. This copy constructor wasn't used, however, when copying was made through the `CUDT` copy constructor, which was using simple assignment inside, and this one was using a generated assignment operator, which was copying the pointer value as well. **Fortunately** nothing wrong happened, as the newly spawned socket for accept was then processed by `CUDT::acceptAndRespond` which was calling inside `CUDT::setupCC` that was calling `configure` on this object, which was overwriting the pointer value anyway, just relying on the name, no matter what was in that pointer before (and it was expected to be NULL there).

In this fix, the provided assignment operator does the same as the constructor, so the pointer value isn't effectively copied. Important thing is that the object claims to own the pointer and it deletes it when it's not NULL at the end.

2. Removed copy constructor for CUDTException.

The copy constructor was intentionally copying all fields, so it was actually duplicating the potentially autogenerated copy constructor. There are also some extra fields there of unknown purpose (their function and existence might need to be revised later), but from the logical point of view they should be copied as well, so a generated copy constructor is still better.

As there's no copy constructor, copy-assignment operator can also stay generated.

3. Assignment to `in_addr` type from `in_addr_t`. This should be a typo that should have been caught by the compiler as type mismatch - only gcc 9 has found it. It wasn't causing any trouble as the effective copying starts at the same address, still it was an error from the language standard point of view.

### CODE REVIEW

**Comment by maxsharabayko** [comment]
As CUDTException is being modified in this PR, please consider fixing #861 by the way.

**Comment by ethouris** [comment]
Good point.

**Comment by ethouris** [comment]
Good point, but the number of changes is too high for this PR. It will be submitted separately.
